### ISSUE TITLE
xcodebuild failed with code 65

### ISSUE THREAD

**Issue by inluxc** [NetrisTV/ws-qvh#10]
Im getting this error after de qvh starts:
Im running appium test with no problem, but with ws-qvh im getting this error.
I have already check the possible fixes witht the setting the team to the WebDriverAgent and nothing.

```
info WebDriverAgent Using WDA path: '/Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/appium-webdriveragent'
info WebDriverAgent Using WDA agent: '/Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj'
info XCUITest Setting up real device
info DevCon Factory Requesting connection for device 00008030-001550A4029A402E on local port 8004, device port 8004
info DevCon Factory Successfully requested the connection for 00008030-001550A4029A402E:8004
info WD Proxy socket hang up
info WebDriverAgent Launching WebDriverAgent on the device
info WebDriverAgent WebDriverAgent does not need a cleanup. The sources are up to date (1626192173947 >= 1626192173947)
info WD Proxy socket hang up
info WD Proxy socket hang up
ERR! WebDriverAgent xcodebuild exited with code '65' and signal 'null'
info WebDriverAgent Launching WebDriverAgent on the device
info WebDriverAgent WebDriverAgent does not need a cleanup. The sources are up to date (1626192173947 >= 1626192173947)
info WD Proxy socket hang up
info WD Proxy socket hang up
info WD Proxy socket hang up
info WD Proxy socket hang up
ERR! WebDriverAgent xcodebuild exited with code '65' and signal 'null'
WARN XCUITest Quitting and uninstalling WebDriverAgent
info WebDriverAgent Shutting down sub-processes
ERR! XCUITest {}
info DevCon Factory Releasing connections for 00008030-001550A4029A402E device on any port number
info DevCon Factory Found cached connections to release: ["00008030-001550A4029A402E:8004"]
info DevCon Factory Releasing the listener for '00008030-001550A4029A402E:8004'
info iProxy@00008030:8004 The connection has been closed
(node:3841) UnhandledPromiseRejectionWarning: Error: Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 65
xcodebuild error message:
. Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md. Try to remove the WebDriverAgentRunner application from the device if it is installed and reboot the device.
    at quitAndUninstall (/Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/appium-xcuitest-driver/lib/driver.js:544:15)
    at /Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/appium-xcuitest-driver/lib/driver.js:579:11
    at wrapped (/Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/asyncbox/lib/asyncbox.js:60:13)
    at retry (/Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/asyncbox/lib/asyncbox.js:43:13)
    at retryInterval (/Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/asyncbox/lib/asyncbox.js:70:10)
    at /Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/appium-xcuitest-driver/lib/driver.js:559:7
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3841) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:3841) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by drauggres** [comment]
As message suggested:
> Make sure you follow the tutorial at https://github.com/appium/appium-xcuitest-driver/blob/master/docs/real-device-config.md

You need to open in Xcode and configure WebDriverAgent project from `/Users/fulviocarvalhido/Projects/Worten/farmer/ws-scrcpy/node_modules/appium-webdriveragent`

**Comment by inluxc** [comment]
Thanks my bad :(
