### ISSUE TITLE
ws-qvh in PATH environment, but not work.

### ISSUE THREAD

**Issue by handywang** [NetrisTV/ws-qvh#13]
I am stuck in "Steps to set up" steps 6th.

I'm sure ws-qvh config is correctly by "which ws-qvh" in Terminal, but when run ws-qvh in Terminal, ws-qvh crashed with following log:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2051dcbe]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2051dcbe
stack: frame={sp:0x7ffeefbff148, fp:0x7ffeefbff198} stack=[0x7ffeefb801e8,0x7ffeefbff250)
0x00007ffeefbff048:  0x01007ffeefbff068  0x0000000000000004 
0x00007ffeefbff058:  0x000000000000001f  0x00007fff2051dcbe 
0x00007ffeefbff068:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff078:  0x0000000004036a51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff118 
0x00007ffeefbff088:  0x00000000042cf7b3  0x00007ffeefbff0d0 
0x00007ffeefbff098:  0x0000000004036d08 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000044fa280 
0x00007ffeefbff0a8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff0b8:  0x00007ffeefbff118  0x0000000004036a51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff0c8:  0x00000000044fa280  0x00007ffeefbff108 
0x00007ffeefbff0d8:  0x0000000004036c90 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff0e8 
0x00007ffeefbff0e8:  0x0000000004036cc0 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000044fa280 
0x00007ffeefbff0f8:  0x0000000004036a51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff118 
0x00007ffeefbff108:  0x00007ffeefbff138  0x0000000004036a51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff118:  0x00007ffeefbff120  0x0000000004036a80 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff128:  0x00000000042d4825  0x000000000000002a 
0x00007ffeefbff138:  0x00007ffeefbff188  0x000000000404c276 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff148: <0x00000000042d4825  0x00000000044fa280 
0x00007ffeefbff158:  0x00007ffeefbff1c8  0x00000000040298e6 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff168:  0x000000c00010e000  0x0000000000002000 
0x00007ffeefbff178:  0x0000000000000008  0x0000000004068100 <runtime.walltime_trampoline+0x0000000000000000> 
0x00007ffeefbff188:  0x00007ffeefbff1d0 !0x00007fff2051dcbe 
0x00007ffeefbff198: >0x00007ffeefbff1d0  0x00000000044a4000 
0x00007ffeefbff1a8:  0x0000000000000343  0x0000000004222825 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff1b8:  0x000000000406873f <runtime.syscall+0x000000000000001f>  0x000000c000058490 
0x00007ffeefbff1c8:  0x00000000040680ac <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c000058460 
0x00007ffeefbff1d8:  0x00000000040665b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff1e8:  0x0000000004010900 <runtime.newarray+0x0000000000000060>  0x0900000000001018 
0x00007ffeefbff1f8:  0x0000000000000010  0x000000000452e1b8 
0x00007ffeefbff208:  0x0000000000000bc8  0x000000c0000001a0 
0x00007ffeefbff218:  0x00000000040646c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff228:  0x0000000004324228  0x00000000044fa280 
0x00007ffeefbff238:  0x00007ffeefbff280  0x00000000040645c5 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff248:  0x000000000406457d <runtime.rt0_go+0x000000000000013d> 
runtime.throw({0x42d4825, 0x44fa280})
	/usr/local/go/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2051dcbe
stack: frame={sp:0x7ffeefbff148, fp:0x7ffeefbff198} stack=[0x7ffeefb801e8,0x7ffeefbff250)
0x00007ffeefbff048:  0x01007ffeefbff068  0x0000000000000004 
0x00007ffeefbff058:  0x000000000000001f  0x00007fff2051dcbe 
0x00007ffeefbff068:  0x0b01dfacedebac1e  0x0000000000000001 
0x00007ffeefbff078:  0x0000000004036a51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff118 
0x00007ffeefbff088:  0x00000000042cf7b3  0x00007ffeefbff0d0 
0x00007ffeefbff098:  0x0000000004036d08 <runtime.fatalthrow.func1+0x0000000000000048>  0x00000000044fa280 
0x00007ffeefbff0a8:  0x0000000000000001  0x0000000000000001 
0x00007ffeefbff0b8:  0x00007ffeefbff118  0x0000000004036a51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff0c8:  0x00000000044fa280  0x00007ffeefbff108 
0x00007ffeefbff0d8:  0x0000000004036c90 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff0e8 
0x00007ffeefbff0e8:  0x0000000004036cc0 <runtime.fatalthrow.func1+0x0000000000000000>  0x00000000044fa280 
0x00007ffeefbff0f8:  0x0000000004036a51 <runtime.throw+0x0000000000000071>  0x00007ffeefbff118 
0x00007ffeefbff108:  0x00007ffeefbff138  0x0000000004036a51 <runtime.throw+0x0000000000000071> 
0x00007ffeefbff118:  0x00007ffeefbff120  0x0000000004036a80 <runtime.throw.func1+0x0000000000000000> 
0x00007ffeefbff128:  0x00000000042d4825  0x000000000000002a 
0x00007ffeefbff138:  0x00007ffeefbff188  0x000000000404c276 <runtime.sigpanic+0x0000000000000396> 
0x00007ffeefbff148: <0x00000000042d4825  0x00000000044fa280 
0x00007ffeefbff158:  0x00007ffeefbff1c8  0x00000000040298e6 <runtime.(*mheap).allocSpan+0x0000000000000546> 
0x00007ffeefbff168:  0x000000c00010e000  0x0000000000002000 
0x00007ffeefbff178:  0x0000000000000008  0x0000000004068100 <runtime.walltime_trampoline+0x0000000000000000> 
0x00007ffeefbff188:  0x00007ffeefbff1d0 !0x00007fff2051dcbe 
0x00007ffeefbff198: >0x00007ffeefbff1d0  0x00000000044a4000 
0x00007ffeefbff1a8:  0x0000000000000343  0x0000000004222825 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005> 
0x00007ffeefbff1b8:  0x000000000406873f <runtime.syscall+0x000000000000001f>  0x000000c000058490 
0x00007ffeefbff1c8:  0x00000000040680ac <runtime.nanotime_trampoline+0x000000000000000c>  0x000000c000058460 
0x00007ffeefbff1d8:  0x00000000040665b0 <runtime.asmcgocall+0x0000000000000070>  0x0000000000000001 
0x00007ffeefbff1e8:  0x0000000004010900 <runtime.newarray+0x0000000000000060>  0x0900000000001018 
0x00007ffeefbff1f8:  0x0000000000000010  0x000000000452e1b8 
0x00007ffeefbff208:  0x0000000000000bc8  0x000000c0000001a0 
0x00007ffeefbff218:  0x00000000040646c9 <runtime.systemstack+0x0000000000000049>  0x0000000000000004 
0x00007ffeefbff228:  0x0000000004324228  0x00000000044fa280 
0x00007ffeefbff238:  0x00007ffeefbff280  0x00000000040645c5 <runtime.mstart+0x0000000000000005> 
0x00007ffeefbff248:  0x000000000406457d <runtime.rt0_go+0x000000000000013d> 
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
syscall.syscall(0x4222820, 0x2, 0x40487413, 0xc000058520)
	/usr/local/go/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000058490 sp=0xc000058470 pc=0x406327b
syscall.syscall(0x400, 0xc000058548, 0x0, 0xc000058540)
	<autogenerated>:1 +0x26 fp=0xc0000584d8 sp=0xc000058490 pc=0x4068ea6
golang.org/x/sys/unix.ioctl(0xc000058520, 0x539ffff, 0x400)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:746 +0x39 fp=0xc000058508 sp=0xc0000584d8 pc=0x42224b9
golang.org/x/sys/unix.IoctlGetTermios(...)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/golang.org/x/sys/unix/ioctl.go:72
github.com/sirupsen/logrus.isTerminal(0x504c9e0)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/terminal_check_bsd.go:11 +0x50 fp=0xc000058578 sp=0xc000058508 pc=0x4224cb0
github.com/sirupsen/logrus.checkIfTerminal({0x4328080, 0xc0000b0010})
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go:13 +0x75 fp=0xc000058590 sp=0xc000058578 pc=0x4224d55
github.com/sirupsen/logrus.(*TextFormatter).init(0xc0000b2240, 0x5700800)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/text_formatter.go:103 +0x34 fp=0xc000058610 sp=0xc000058590 pc=0x4224e34
github.com/sirupsen/logrus.(*TextFormatter).Format.func1()
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/text_formatter.go:193 +0x25 fp=0xc000058630 sp=0xc000058610 pc=0x42264e5
sync.(*Once).doSlow(0x432d298, 0xc0000a6168)
	/usr/local/go/src/sync/once.go:68 +0xd2 fp=0xc000058698 sp=0xc000058630 pc=0x406cfd2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc0000b2240, 0xc0000f60e0)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/text_formatter.go:193 +0xebe fp=0xc000058c08 sp=0xc000058698 pc=0x4225e9e
github.com/sirupsen/logrus.(*Entry).write(0xc0000f60e0)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/entry.go:275 +0xa5 fp=0xc000058c80 sp=0xc000058c08 pc=0x42233a5
github.com/sirupsen/logrus.Entry.log({0xc0000f6000, 0xc00009b290, {0x0, 0x0, 0x0}, 0x0, 0x0, {0x0, 0x0}, 0x0, ...}, ...)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/entry.go:251 +0x285 fp=0xc000058d00 sp=0xc000058c80 pc=0x4223045
github.com/sirupsen/logrus.(*Entry).Log(0xc0000f6070, 0x4, {0xc000058e30, 0x422405a, 0xc0000f6040})
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/entry.go:287 +0xa8 fp=0xc000058e08 sp=0xc000058d00 pc=0x42235c8
github.com/sirupsen/logrus.(*Entry).Logln(0xc0000f6070, 0x4, {0xc000058f40, 0x42c4280, 0xc000000101})
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/entry.go:378 +0x85 fp=0xc000058e50 sp=0xc000058e08 pc=0x4223785
github.com/sirupsen/logrus.(*Entry).Infoln(...)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/entry.go:391
github.com/sirupsen/logrus.(*Entry).Println(...)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/entry.go:395
github.com/sirupsen/logrus.(*Logger).Println(0xc0000f6000, {0xc000058f40, 0x1, 0x1})
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/logger.go:259 +0x51 fp=0xc000058e90 sp=0xc000058e50 pc=0x4224651
github.com/sirupsen/logrus.Println(...)
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/vendor/github.com/sirupsen/logrus/exported.go:194
main.startWebSocketServer({0x7ffeefbff527, 0x6})
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/main.go:33 +0x7c fp=0xc000058f60 sp=0xc000058e90 pc=0x424b65c
main.main()
	/Users/dynamicui/Downloads/3.AMapProj/NetrisTV/ws-qvh/main.go:29 +0x56 fp=0xc000058f80 sp=0xc000058f60 pc=0x424b5b6
runtime.main()
	/usr/local/go/src/runtime/proc.go:255 +0x227 fp=0xc000058fe0 sp=0xc000058f80 pc=0x40390e7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x40668a1
	
```	
So, did any steps I miss? pls let me know that ,thanks.

**Comment by drauggres** [comment]
Hi. For some reason logger does not like you terminal. Application crashes on main.go:33:
https://github.com/NetrisTV/ws-qvh/blob/068ea8421e661e123342b9fe918c13555701eb3f/main.go#L33

If you are using it with `ws-scrcpy`, you don't need to run `ws-qvh` manually.


UPD: see https://github.com/sirupsen/logrus/issues/1275

**Comment by drauggres** [comment]
@handywang Please, check latest version.
